### ISSUE TITLE
[Bug]: EfficientAD Lightning Model for larger datasets - CUDA memory error when calculating teacher mean and std

### ISSUE THREAD

**Issue by holzweber** [openvinotoolkit/anomalib#1525]
### Describe the bug

I am currently working with a custom dataset in mvtec format consisting of 5000 train images with the shape (1024, 1024).
I am using the EfficientAD model for this task.

When calculating the teacher mean and std there is a memory issue for both, CPU and GPU usage, in which the memory consumption grows linear during the iteration even with a small batchsize of 1.

The exact problem are the following two lines in the library, where we accumulate to much memory during the adding of the tensors (the memory does somehow increase):
https://github.com/openvinotoolkit/anomalib/blob/1f50c952fc65a165884b2b94e178821dcebfbbef/src/anomalib/models/efficient_ad/lightning_model.py#L152

### Dataset

Other (please specify in the text field below)

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

from anomalib.config import get_configurable_parameters
from anomalib.data import get_datamodule
from anomalib.data.utils import TestSplitMode
from anomalib.models import get_model
from anomalib.utils.callbacks import LoadModelCallback, get_callbacks
from anomalib.utils.loggers import configure_logger, get_experiment_logger

config = get_configurable_parameters(model_name="efficient_ad", config_path="config.yaml")

datamodule = get_datamodule(config)
model = get_model(config)
experiment_logger = get_experiment_logger(config)
callbacks = get_callbacks(config)

trainer = Trainer(**config.trainer, logger=experiment_logger, callbacks=callbacks)
trainer.fit(model=model, datamodule=datamodule)

### OS information

OS information:
- OS: Windows
- Python version: 3.10
- Anomalib version: 0.7.0
- PyTorch version: 2.1.0
- CUDA/cuDNN version: 12.1
- GPU models and configuration: 2x NVIDIA TITAN RTX à 24GB
- Any other relevant information: I'm using a custom dataset with 5000 images of size 1024, 1024, Training in a Jupyter Notebook

### Expected behavior

I would expect, that the calculation of the mean and std is possible without a cuda out of memory error.

**Possible Solution**
A solution would be, that the model is set to evaluation/inference mode, when calculating the mean and std in the following method (teacher_channel_mean_std), as just setting no_grad is not enough:
https://github.com/openvinotoolkit/anomalib/blob/1f50c952fc65a165884b2b94e178821dcebfbbef/src/anomalib/models/efficient_ad/lightning_model.py#L126C12-L126C12

### Pip/GitHub

pip

### Configuration YAML

```yaml
dataset:
    name: mvtec
    format: mvtec
    path: ../../validation/data/mvtec
    category: "myclass"
    task: segmentation
    train_batch_size: 1
    eval_batch_size: 1
    num_workers: 8
    image_size: 1024 # dimensions to which images are resized (mandatory)
    calculate_image_size: True
    center_crop: null # dimensions to which images are center-cropped after resizing (optional)
    normalization: none # data distribution to which the images will be normalized: [none, imagenet]
    transform_config:
        train: null
        eval: null
    test_split_mode: from_dir # options: [from_dir, synthetic]
    test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
    val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
    val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
    name: efficient_ad
    teacher_out_channels: 384
    model_size: small # options: [small, medium]
    lr: 0.0001
    weight_decay: 0.00001
    padding: false
    pad_maps: true # relevant for "padding: false", see EfficientAd in lightning_model.py
    # generic params
    normalization_method: min_max # options: [null, min_max, cdf]
    min_error_pixel: 5
metrics:
    image:
        - F1Score
        - AUROC
    pixel:
        - F1Score
        - AUROC
    threshold:
        method: adaptive #options: [adaptive, manual]
        manual_image: null
        manual_pixel: null

visualization:
    show_images: False # show images on the screen
    save_images: True # save images to the file system
    log_images: False # log images to the available loggers (if any)
    image_save_path: null # path to which images will be saved
    mode: full # options: ["full", "simple"]

project:
    seed: 42
    path: ./results

logging:
    logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
    log_graph: false # Logs the model graph to respective logger.

optimization:
    export_mode: null # options: torch, onnx, openvino
# PL Trainer Args. Don't add extra parameter here.
trainer:
    enable_checkpointing: true
    default_root_dir: null
    gradient_clip_val: 0
    gradient_clip_algorithm: norm
    num_nodes: 1
    devices: 1
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    accumulate_grad_batches: 1
    max_epochs: 1 # 200
    min_epochs: null
    max_steps: 50 #70000
    min_steps: null
    max_time: null
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    log_every_n_steps: 2 # 50
    accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
    strategy: null
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    num_sanity_val_steps: 0
    profiler: null
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    plugins: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[33], line 2
      1 trainer = Trainer(**config.trainer, logger=experiment_logger, callbacks=callbacks)
----> 2 trainer.fit(model=model, datamodule=datamodule)

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\trainer\trainer.py:608, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    606 model = self._maybe_unwrap_optimized(model)
    607 self.strategy._lightning_module = model
--> 608 call._call_and_handle_interrupt(
    609     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    610 )

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\trainer\call.py:38, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     36         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
     37     else:
---> 38         return trainer_fn(*args, **kwargs)
     40 except _TunerExitException:
     41     trainer._call_teardown_hook()

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\trainer\trainer.py:650, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    643 ckpt_path = ckpt_path or self.resume_from_checkpoint
    644 self._ckpt_path = self._checkpoint_connector._set_ckpt_path(
    645     self.state.fn,
    646     ckpt_path,  # type: ignore[arg-type]
    647     model_provided=True,
    648     model_connected=self.lightning_module is not None,
    649 )
--> 650 self._run(model, ckpt_path=self.ckpt_path)
    652 assert self.state.stopped
    653 self.training = False

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\trainer\trainer.py:1112, in Trainer._run(self, model, ckpt_path)
   1108 self._checkpoint_connector.restore_training_state()
   1110 self._checkpoint_connector.resume_end()
-> 1112 results = self._run_stage()
   1114 log.detail(f"{self.__class__.__name__}: trainer tearing down")
   1115 self._teardown()

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\trainer\trainer.py:1191, in Trainer._run_stage(self)
   1189 if self.predicting:
   1190     return self._run_predict()
-> 1191 self._run_train()

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\trainer\trainer.py:1214, in Trainer._run_train(self)
   1211 self.fit_loop.trainer = self
   1213 with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1214     self.fit_loop.run()

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\loops\loop.py:194, in Loop.run(self, *args, **kwargs)
    190     return self.on_skip()
    192 self.reset()
--> 194 self.on_run_start(*args, **kwargs)
    196 while not self.done:
    197     try:

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\loops\fit_loop.py:218, in FitLoop.on_run_start(self)
    215 self._results.to(device=self.trainer.lightning_module.device)
    217 self.trainer._call_callback_hooks("on_train_start")
--> 218 self.trainer._call_lightning_module_hook("on_train_start")
    219 self.trainer._call_strategy_hook("on_train_start")

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\pytorch_lightning\trainer\trainer.py:1356, in Trainer._call_lightning_module_hook(self, hook_name, pl_module, *args, **kwargs)
   1353 pl_module._current_fx_name = hook_name
   1355 with self.profiler.profile(f"[LightningModule]{pl_module.__class__.__name__}.{hook_name}"):
-> 1356     output = fn(*args, **kwargs)
   1358 # restore current_fx when nested context
   1359 pl_module._current_fx_name = prev_fx_name

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\anomalib\models\efficient_ad\lightning_model.py:216, in EfficientAd.on_train_start(self)
    214 """Calculate or load the channel-wise mean and std of the training dataset and push to the model."""
    215 if not self.model.is_set(self.model.mean_std):
--> 216     channel_mean_std = self.teacher_channel_mean_std(self.trainer.datamodule.train_dataloader())
    217     self.model.mean_std.update(channel_mean_std)

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\torch\utils\_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\anomalib\models\efficient_ad\lightning_model.py:141, in EfficientAd.teacher_channel_mean_std(self, dataloader)
    139 logger.info("Calculate teacher channel mean and std")
    140 for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean", position=0, leave=True):
--> 141     y = self.model.teacher(batch["image"].to(self.device))
    142     y_means.append(torch.mean(y, dim=[0, 2, 3]))
    143     teacher_outputs.append(y)

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\anomalib\models\efficient_ad\torch_model.py:76, in PDN_S.forward(self, x)
     74 def forward(self, x):
     75     x = imagenet_norm_batch(x)
---> 76     x = F.relu(self.conv1(x))
     77     x = self.avgpool1(x)
     78     x = F.relu(self.conv2(x))

File C:\Applications\Miniconda\envs\epp_next\lib\site-packages\torch\nn\functional.py:1471, in relu(input, inplace)
   1469     result = torch.relu_(input)
   1470 else:
-> 1471     result = torch.relu(input)
   1472 return result

OutOfMemoryError: CUDA out of memory. Tried to allocate 1.99 GiB. GPU 0 has a total capacty of 24.00 GiB of which 0 bytes is free. Of the allocated memory 17.60 GiB is allocated by PyTorch, and 4.43 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holzweber** [comment]
> Hello, thanks for reporting this. Similar thing happens in #1495. I too think that the problem is in the lines you mentioned, but I though that `no_grad` was enough to disable gradient memory accumulation. Can you confirm that issue is resolved by putting model into eval mode, as I'm not sure if it's not some deeper problem.

Hey!

Yes at least for my test setup as described, it solved the memory issue.
You can either change the annotation from @torch.no_grads to @torch.inference_mode or you set self.model.teacher.eval() (and later train() again)

I will create a PR for the @torch.inference, however I can not confirm that this also works for the other issue.

**Comment by blaz-r** [comment]
Great. Thanks.

**Comment by fhf526** [comment]
@holzweber Hey!  I still run efficient_ad, and as the calculation increases, OutOfMemoryError: CUDA out of memory is displayed.

**Comment by holzweber** [comment]
> @holzweber Hey! I still run efficient_ad, and as the calculation increases, OutOfMemoryError: CUDA out of memory is displayed.

Hey!
Which version you are running on? If you did the pip install with version 0.8.0 try to use the following install:
pip install git+https://github.com/openvinotoolkit/anomalib@911a892207489a9ddc7a59bb06576d4021fda62c

Can you tell if this solves your problem? - If yes, you just have an outdated version

**Comment by fhf526** [comment]
> > 嘿！我仍然运行efficient_ad，随着计算的增加，显示 OutOfMemoryError： CUDA out of memory。
> 
> 嘿！您运行的是哪个版本？如果您使用版本 0.8.0 进行了 pip 安装，请尝试使用以下安装：pip install git+https://github.com/openvinotoolkit/anomalib@911a892207489a9ddc7a59bb06576d4021fda62c
> 
> 你能判断这是否解决了你的问题吗？- 如果是，您只是有一个过时的版本
hey! Thank you very much for your reply!
Is the version view in **src/anomalib/_init_.py**?   Inside is **__version__ = "1.0.0dev"**
I use the command you sent to install, will prompt "note: This error originates from a subprocess, and is likely not a problem with pip."
I have just observed the latest **main** branch update, does this latest **main** branch solve the problem?

**Comment by holzweber** [comment]
> > > 嘿！我仍然运行efficient_ad，随着计算的增加，显示 OutOfMemoryError： CUDA out of memory。
> > 
> > 
> > 嘿！您运行的是哪个版本？如果您使用版本 0.8.0 进行了 pip 安装，请尝试使用以下安装：pip install git+https://github.com/openvinotoolkit/anomalib@911a892207489a9ddc7a59bb06576d4021fda62c
> > 你能判断这是否解决了你的问题吗？- 如果是，您只是有一个过时的版本
> > hey! Thank you very much for your reply!
> > Is the version view in **src/anomalib/_init_.py**?   Inside is **version = "1.0.0dev"**
> > I use the command you sent to install, will prompt "note: This error originates from a subprocess, and is likely not a problem with pip."
> > I have just observed the latest **main** branch update, does this latest **main** branch solve the problem?

So you are already on 1.0.0dev? This should have the changes already I think.
At least my problem was solved installing the main branch (from source) and not installing via pip

**Comment by fhf526** [comment]
> So you are already on 1.0.0dev? This should have the changes already I think. At least my problem was solved installing the main branch (from source) and not installing via pip

Yes, I downloaded the **main** branch code, can you tell me which code is modified? I'll check it out. Thank you very much!

**Comment by holzweber** [comment]
> > So you are already on 1.0.0dev? This should have the changes already I think. At least my problem was solved installing the main branch (from source) and not installing via pip
> 
> Yes, I downloaded the **main** branch code, can you tell me which code is modified? I'll check it out. Thank you very much!

I did not work with v1 so far, I think the training concept is different (maybe you can see more in the readme)
I am currently working on the https://github.com/openvinotoolkit/anomalib@911a892207489a9ddc7a59bb06576d4021fda62c branch. Pull this one, pip install from source and test your app
